name: vouchercodes-task Playwright Tests
run-name: vouchercodes-task Playwright Tests${{ inputs.tests != '' && format(' ({0})', inputs.tests) || '' }} - ${{ inputs.browser != '' && format(' against {0}', inputs.browser) || '' }}

on:
  pull_request:
    branches: [ main, master ]

  workflow_dispatch:
    inputs:
      tests:
        description: "Tests to run (wrap in commas and separate tests with spaces)"
        required: false
        default: ""
      browser:
        description: "Browser (all/chrome/firefox/webkit)"
        required: true
        default: "chrome"
        type: choice
        options:
          - all
          - chrome
          - firefox
          - webkit

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        browser: ${{ fromJson(inputs.browser == 'all' && '["chrome", "firefox", "webkit"]' || format('["{0}"]', inputs.browser)) }}
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      if: ${{ inputs.browser == 'all' || inputs.browser == matrix.browser }}
      run: |
        tests="${{ inputs.tests }}"
        browser="${{ matrix.browser }}"

        declare -A browser_map=(
          [chrome]="chromium"
          [firefox]="firefox"
          [webkit]="webkit"
        )

        project="${browser_map[$browser]}"
        echo "Running tests with browser: $browser (project: $project)"

        if [ -n "$tests" ]; then
          echo "Running: npx playwright test $tests --reporter=html,line --project=$project"
          npx playwright test $tests --reporter=html,line --project="$project"
        else
          echo "Running: npx playwright test --reporter=html,line --project=$project"
          npx playwright test --reporter=html,line --project="$project"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BROWSER: ${{ matrix.browser }}
        PLAYWRIGHT_JSON_OUTPUT_NAME: summary.json

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ matrix.browser }}
        path: playwright-report
        retention-days: 30